version: '3.4'
volumes:
  dbdata:
services:
  db:
    image: postgres:9.6-alpine
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
     - dbdata:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=developmentpassword

  middleman:
    build:
      context: .
      target: middleman
      cache_from:
        - ${dockerHubUsername:-dfedigital}/teacher-training-api-middleman:master
    image: ${dockerHubUsername:-dfedigital}/teacher-training-api-middleman:${GIT_BRANCH:-latest}

  web:
    build:
      context: .
      cache_from:
        - ${dockerHubUsername:-dfedigital}/teacher-training-api:${GIT_BRANCH:-latest}
        - ${dockerHubUsername:-dfedigital}/teacher-training-api-middleman:${GIT_BRANCH:-latest}
    image: ${dockerHubUsername:-dfedigital}/teacher-training-api:${GIT_BRANCH:-latest}
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
      - middleman
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - CC_TEST_REPORTER_ID=${CC_TEST_REPORTER_ID}
      - AGENT_JOBSTATUS=${AGENT_JOBSTATUS}
      - GIT_BRANCH=${GIT_BRANCH}

  bg-geocode:
    build:
      args:
        - DOCKER_REPOSITORY=${dockerHubUsername:-dfedigital}
        - TEACHER_TRAINING_API=${dockerHubImageName:-teacher-training-api}
      context: bg-geocode
      cache_from:
        - ${dockerHubUsername:-dfedigital}/teacher-training-bg-geocode:${GIT_BRANCH:-latest}
    image: ${dockerHubUsername:-dfedigital}/teacher-training-bg-geocode:${GIT_BRANCH:-latest}
    volumes:
      - .:/app
    depends_on:
      - web
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - SETTINGS__APPLICATION=teacher-training-api-bg-geocode

  bg-mailer:
    build:
      args:
        - DOCKER_REPOSITORY=${dockerHubUsername:-dfedigital}
        - TEACHER_TRAINING_API=${dockerHubImageName:-teacher-training-api}
      context: bg-mailer
      cache_from:
        - ${dockerHubUsername:-dfedigital}/teacher-training-bg-mailer:${GIT_BRANCH:-latest}
    image: ${dockerHubUsername:-dfedigital}/teacher-training-bg-mailer:${GIT_BRANCH:-latest}
    volumes:
      - .:/app
    depends_on:
      - web
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - SETTINGS__APPLICATION=teacher-training-api-bg-mailer

  bg-jobs:
    build:
      args:
        - DOCKER_REPOSITORY=${dockerHubUsername:-dfedigital}
        - TEACHER_TRAINING_API=${dockerHubImageName:-teacher-training-api}
      context: bg-jobs
    image: ${dockerHubUsername:-dfedigital}/teacher-training-bg-jobs:${GIT_BRANCH:-latest}
    volumes:
      - .:/app
    depends_on:
      - web
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - SETTINGS__APPLICATION=teacher-training-api-bg-mailer
