default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_DATABASE'] %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE', 'manage_courses_backend_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') { "manage_courses_backend_test#{ENV['TEST_ENV_NUMBER']}" } %>

staging:
  <<: *default

qa:
  <<: *default

pentest:
  <<: *default

research:
  <<: *default

production:
  <<: *default
